### ISSUE TITLE
Read/write/preserve comments (roundtrip config)

### ISSUE THREAD

**Issue by eugenesvk** [tabatkins/kdlpy#10]
One of the issues with using a textual config format is that it usually prevents both the user and the app from editing it since the app overwrites user formatting or even data like comments

So I was wondering whether it'd be possible to preserve comments on read/edits of the KDL docs with your library? And ideally also all whitespace from the source

**Comment by tabatkins** [comment]
Not my library, no. The data format required to preserve comments and whitespace requires a substantially different approach, and makes it less suitable for general purpose usage. You end up with a *very* different-looking set of data structures, and it's a lot harder to work with.

Having the file auto-modifiable by the app *as well as* users is a pretty hard problem in general; a lot of possible edits end up with an unclear serialization afterwards. Like, if you remove a node, how do you handle its surrounding whitespace? You don't *really* just want a blank line, usually. If you're doing this, generally what you want is to eagerly canonicalize the file whenever the user edits it. That somewhat limits the user's ability to customize how they write their config, but it comes with its own benefits, as it's effectively an auto-linter as well.

**Comment by eugenesvk** [comment]
> You don't really just want a blank line, usually

But that's such a minor thing compared to the app destroying all your comments and all your sorting and formatting (or the app being unable to even generate comments).

For linting you can feed your app rules/schemes to an LSP  if you like and let the user decide whether it's a benefit or not
