### ISSUE TITLE
Support for KDL schema

### ISSUE THREAD

**Issue by eugenesvk** [tabatkins/kdlpy#13]
KDL specifies a schema https://github.com/kdl-org/kdl/blob/main/SCHEMA-SPEC.md that can be used to help avoid configuration errors.

Is it possible to use it with your library?

**Comment by tabatkins** [comment]
I currently have nothing to do the KDL Schema and haven't paid any attention to how it works. I don't currently have any plans to add Schema support, tho it might be an interesting project later.
