### ISSUE TITLE
Insertion order of node properties is not respected while printing

### ISSUE THREAD

**Issue by LemmaEOF** [tabatkins/kdlpy#2]
The `Node` class requires an `OrderedDict` for properties, indicating that the order that properties are inserted in is respected. However, in the `print` function, the `props` field is [passed through the `sorted` function](https://github.com/tabatkins/kdlpy/blob/main/kdl/types.py#L64), breaking this expectation. This is not configurable and can end up preventing accurate round-tripping of kdl documents.

Example code:
```py
from kdl import Document, Node, parse

doc = Document(
    nodes=[
        Node(name="test", props=OrderedDict("b": 1, "a": 2))  # `b` is inserted first
    ]
)

print(contents = doc.print())  # prints `test a=2 b=1\n`
```

The best resolutions for this issue would be to either remove this call to `sorted` or change the type of `props` to be a standard `Dict` instead of an `OrderedDict`  to indicate that insertion order is not expected to be preserved.

**Comment by tabatkins** [comment]
Ah right, the test suite requires them sorted alphabetically. I'll just hide that behind a PrintConfig option.
