### ISSUE TITLE
ParseFragment should be in public API

### ISSUE THREAD

**Issue by clarfonthey** [tabatkins/kdlpy#3]
Since it's provided to converters when calling them, it should be importable as `kdl.ParseFragment`.

**Comment by tabatkins** [comment]
My thought was that there's never any reason to create one, so exposing it wasn't very necessary.

Tho hm, I suppose you do need access to it to write type signatures, if nothing else. Okay, I'll export it.

**Comment by tabatkins** [comment]
And cut a new version 1.0.6.

**Comment by clarfonthey** [comment]
Thank you!

And yeah, I'm not exactly sure how you could export it as just a type definition and not the class itself, but at least for the moment it's useful for type definitions.
