### ISSUE TITLE
Invalid single line comment instead as a terminator

### ISSUE THREAD

**Issue by eugenesvk** [tabatkins/kdlpy#4]
Single line comments are allowed to terminate per Spec
`node-terminator = ";"|eof|single-line-comment|newline`
but 
```
n fail=1 //
```
fails with a `kdl.errors.ParseError: 1:7 parse error: Junk after node, before terminator.` error
```
n ok=1;
```
using v1.1.0

**Comment by tabatkins** [comment]
Sorry for the dealy, issue fixed in 1.1.2.
