### ISSUE TITLE
Regex match for valueConverters?

### ISSUE THREAD

**Issue by eugenesvk** [tabatkins/kdlpy#7]
If I have slightly more complicated types consisting of 3 subtypes `i`,`n`,`v` (any combination, any order, so `in` or `nv` etc), would it be possible to add an option to have `valueConverters` match by regex instead of a string literal (so that a filter could, for example, reorder these types and replace them with longer names?)?

**Comment by tabatkins** [comment]
Hm, yeah, I could allow regexes in valueConverters, and also in NodeKeys.

**Comment by tabatkins** [comment]
All right, regexes are supported in NodeKeys now, and at this point we're getting powerful enough to justify going all the way and allowing arbitrary functions, so that's allowed too.

**Comment by tabatkins** [comment]
Lol closed this too early, it was actually about *value* converters. Those are fixed up too, now!

valueConverters now uses ValueKey as its key type, which can be a TagKey (like nodeConverters) or a (TagKey, TypeKey) tuple (where TypeKey can be `...` or something you can pass to `isinstance()`).

For convenience, I've also added `node.getProps(ValueKey)` and `node.getArgs(ValueKey)` methods, for filtering args/methods by ValueKeys after construction, too.

Everything should be well-documented in the README now, too.

Okay, so one last thing to do is implement `NotImplemented` support, so one converter can pass the value on to another later one.

**Comment by tabatkins** [comment]
Okay, version 1.2.0 released. Please let me know if this serves your needs, and if you run into any issues!
