### ISSUE TITLE
NodeConverters for any untagged node fails (None, None)

### ISSUE THREAD

**Issue by eugenesvk** [tabatkins/kdlpy#8]
In this test I can catch an `import` node with not name when `nodeConverters` are `(None,"import")`, but not when they're `(None,None)` even though the latter is supposed to match any tagless node "(None, None): matches nodes with no tag, regardless of name."

```py
def test_construct_kdl3():
  test_kdl = """import k=true"""
  def fn_node(kdl_py_obj, parse_fragment):
    print(f"fn_node kdl_py_obj = |{kdl_py_obj}|") # full node
    print(f"fn_node parse_fragment = |{parse_fragment.fragment}|") # node_name
    return kdl_py_obj
  parseConfig = kdl.ParseConfig(nodeConverters={(None,None):fn_node}) # fails
  # parseConfig = kdl.ParseConfig(nodeConverters={(None,"import"):fn_node}) # works
  printConfig = kdl.printing.defaults
  doc = kdl.Parser(parseConfig, printConfig).parse(test_kdl)
test_construct_kdl3()
```

**Comment by tabatkins** [comment]
Nice catch, I was just doing something stupid during node construction and not actually executing the NodeKey match properly. Should be fixed now, I'll push a new version momentarily.

**Comment by tabatkins** [comment]
1.1.7 released; let me know if that works for you or if anything's still weird!
